#!/bin/sh

ENABLECARD=/usr/local/bin/ironhide-enablecard
DISABLECARD=/usr/local/bin/ironhide-disablecard

####
## This script disables nVidia card if no optirun is running.
####
if ! pidof -x /usr/bin/optirun /usr/bin/optirun32 /usr/bin/optirun64 >/dev/null; then
#	$ENABLECARD
if [[ `lspci -v -s 01:00 | grep "\!" |wc -l` = 0 ]]; then
	$DISABLECARD
fi

fi
