#!/bin/bash

### BEGIN LICENSE
#
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <davy.renaud@laposte.net> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return Davy Renaud (glyptostroboides)
# ----------------------------------------------------------------------------
#

#    This file is part of ironhide.
#
#    ironhide is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ironhide is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ironhide.  If not, see <http://www.gnu.org/licenses/>.
#
### END LICENSE


### COMMENT
#This is a optirun script which takes arguments: frame transfer, architecture, display (just for testing purpose).
#If the force argument is omitted, the script will not launch the app with ironhide if the computer is on battery
#Usage :
#	optirun -f -32 -c <frame_transfer_value> -d <display value>
# -f : Force optirun : force the app to be run with ironhide if on battery
# -32 : 32Bits library : use the 32bits Nvidia driver (optirun -32 is equivalent to optirun32)
# -c <frame_transfer_value> : Frame transfer : -c must be followed by jpeg, proxy, rgb, yuv or xv argument (See the VGL doc)
# -d <display_value> : -d must be followed by :0, :1 or :2 argument (See the VGL doc)
### END COMMENT

LOCALECONFIGFILE=.ironhiderc

#DEFAULT VALUE
VGL_DRIVER="/usr/lib/nvidia-current"
NVIDIABUSID=`grep BusID /etc/X11/xorg.conf.nvidia | sed -e "s/[ \t]*BusID[ \t]*\"\(.*\)\"/\1/g" |cut -d: -f2,3`
DELAY=1 # Time to let applications settle, before trying to shutdown the nvidia card..

source /etc/default/ironhide
if [ -f ~/$LOCALECONFIGFILE ];then
	source ~/$LOCALECONFIGFILE
fi

while :; do
	case "$1" in
	  -f)
		ECO_MODE='0'
		echo "The application will be run with Ironhide even if it's not connected to a power supply (e.g. running on battery)"
		;; #force optirun if on battery
	  -32)
		VGL_DRIVER="/usr/lib32/nvidia-current"
		echo "The 32-bit nVidia driver will be used"
		;; #launch vglrun with 32 bits nvidia driver
	  -c)
		shift
		case "$1" in
		  jpeg|proxy|rgb|yuv|xv)
			VGL_COMPRESS=$arg
			echo "Ironhide will transfer frames using : $VGL_COMPRESS"
			;;
		*)
			echo "The frame transfer parameter -c must be followed by jpeg, proxy, rgb, yuv or xv."
			exit 3
			;;
		esac
		;;
	  -d)
		shift
		if ! [[ $1 =~ ^:[0-9]+$ ]]; then
			VGL_DISPLAY=$1
			echo "Ironhide will use the $VGL_DISPLAY display for rendering"
		else
			echo "The display parameter -d must be followed by a colon and digits like :8"
			exit 2
		fi
		;;
	  --)
		# commonly found in parameters, usage: optirun -- -not -recognised -as -param
		break
		;;
	  -*)
		echo "Unknown parameter: $1"
		exit 3
		;;
	  *)
		# begin of a command, assuming no optirun parameters after this one
		break
		;;
	esac
	# move to the next option in the command
	shift
done

# if executed from a symlink named optirun32, use the 32b path if exist
if [ "${0##*/}" = "optirun32" -a -d /usr/lib32/nvidia-current ]; then
	VGL_DRIVER=/usr/lib32/nvidia-current
fi

for arg in $@; do

if [[ `echo $arg | grep wine` -eq 0  ]]; then

if [[ `file $arg | grep 64-bit |wc -l` -ne 0 ]];then
        VGL_DRIVER=/usr/lib/nvidia-current
        break
elif [[ `file $arg | grep 32-bit |wc -l` -ne 0 ]];then
        VGL_DRIVER=/usr/lib32/nvidia-current
	break
fi

fi
                                 
done

msg_shown=false
show_msg() {
	if ! $msg_shown; then
		echo "Another ironhide powered application is running, keeping ironhide alive."
		msg_shown=true
	fi
}

#OPTIRUN
optirun_launcher() {
	# Remove colon and everything before it: :1.0 -> 1.0
	display=${VGL_DISPLAY##*:}
	# Remove dot and everything after it: 1.0 -> 1
	display=${display%%.*}

	# test if Ironhide's X server is running
	if [ ! -f /tmp/.X${display}-lock ]; then
		# Ironhide starts the X server on its own. If it was already running,
		# it still returns 0 so no need for checking if the card is enabled or not
		if ! sudo /etc/init.d/ironhide enable; then
			echo "ironhide could not be started - optirun cannot be executed."
			exit 1
		fi
	fi
	# If for some reason the card is still disabled, enable it. This should
	# never happen though!
	if lspci -v -s $NVIDIABUSID | grep -q !; then
		if [ -x /usr/local/bin/ironhide-enablecard ]; then
			echo "Something strange is going on. The card was still disabled even though X started without issues. Please report this"
			sudo /usr/local/bin/ironhide-enablecard
		fi
	fi

	trap "echo 'Caught Ctrl+C'" INT

	######MODIFICATION######Comment : source /etc/default/ironhide

	export VGL_READBACK
	export VGL_LOG
	######MODIFICATION######Replace : /usr/lib/nvidia-current with $VGL_DRIVER
	vglrun -c $VGL_COMPRESS -d $VGL_DISPLAY -ld "$VGL_DRIVER" "$@"
	sleep $DELAY
	if [ "$STOP_SERVICE_ON_EXIT" != "NO" ]; then
		OPTIRUNS="/usr/bin/optirun /usr/bin/optirun32 /usr/bin/optirun64"
		while :; do
			if [[ `lsof -n -w /usr/lib*/nvidia-current/libnvidia-glcore.so* | wc -l` > 0 ]]; then
				show_msg
				sleep 1
			else
				break
			fi
		done
		if ! lspci -v -s $NVIDIABUSID | grep -q !; then
			sudo /etc/init.d/ironhide disable
		fi
	fi

}

#CHECK IF ON BATTERY OR NOT

POWER_STATE=0
for state in /sys/class/power_supply/*/online; do
	POWER_STATE=$(cat "$state")
	break
done

if [ "$POWER_STATE" -eq "1" ] || [ "$ECO_MODE" -eq "0" ]; then
	optirun_launcher "$@"
elif [ "$POWER_STATE" -eq "0" ]; then
	"$@"
else
	"$@"
fi

