#!/bin/bash
HEIGHT=500
WIDTH=700
source easybashgui


if [ `$LSPCI -v -s $NVIDIABUSIDCUT |grep ! |wc -l` = 1 ]; then
        if [ -f /usr/local/bin/ironhide-enablecard ]; then
                        /usr/local/bin/ironhide-enablecard
                                fi
                                        if [ -f /usr/bin/ironhide-enablecard ]; then
                                                        /usr/bin/ironhide-enablecard
                                                                fi
                                                                fi
                                                                ${MODPROBE} nvidia-current
                                                                if [ `$LSPCI -v -s $NVIDIABUSIDCUT |grep ! |wc -l` = 0 ] ; then
                                                                         if [ `LD_LIBRARY_PATH=/usr/lib/nvidia-current /usr/lib/nvidia-current/bin/nvidia-xconfig --query-gpu-info | grep "Display Devices" | cut -f2 -d":"` -gt 0 ] ; then
                                                                                          CONNECTEDMONITOR=`LD_LIBRARY_PATH=/usr/lib/nvidia-current /usr/lib/nvidia-current/bin/nvidia-xconfig --query-gpu-info | grep "Display Device 0" | cut -f2
                                                                                                  fi
                                                                                                  fi
                                                                                                  ${MODPROBE} -r nvidia
                                                                                                  fi
                                                                                                  if [ `$LSPCI -v -s $NVIDIABUSIDCUT |grep ! |wc -l` = 0 ]; then
                                                                                                          if [ -f /usr/local/bin/ironhide-disablecard ]; then
                                                                                                                          /usr/local/bin/ironhide-disablecard
                                                                                                                                  fi
                                                                                                                                          if [ -f /usr/bin/ironhide-disablecard ]; then
                                                                                                                                                          /usr/bin/ironhide-disablecard
                                                                                                                                                                  fi
                                                                                                                                                                  fi
                                                                                                                                                                  